import { Language } from '@/app/types';

export const languages: Record<Language, string> = {
  en: 'English',
  hi: 'हिंदी',
  ta: 'தமிழ்',
  te: 'తెలుగు',
  bn: 'বাংলা',
};

export const translations: Record<string, Record<Language, string>> = {
  // Navigation
  home: {
    en: 'Home',
    hi: 'होम',
    ta: 'முகப்பு',
    te: 'హోమ్',
    bn: 'হোম',
  },
  lessons: {
    en: 'Lessons',
    hi: 'पाठ',
    ta: 'பாடங்கள்',
    te: 'పాఠాలు',
    bn: 'পাঠ',
  },
  quizzes: {
    en: 'Quizzes',
    hi: 'प्रश्नोत्तरी',
    ta: 'வினாடி வினா',
    te: 'క్విజ్‌లు',
    bn: 'কুইজ',
  },
  progress: {
    en: 'Progress',
    hi: 'प्रगति',
    ta: 'முன்னேற்றம்',
    te: 'పురోగతి',
    bn: 'অগ্রগতি',
  },
  dashboard: {
    en: 'Dashboard',
    hi: 'डैशबोर्ड',
    ta: 'முகப்புப் பலகை',
    te: 'డాష్‌బోర్డ్',
    bn: 'ড্যাশবোর্ড',
  },
  students: {
    en: 'Students',
    hi: 'छात्र',
    ta: 'மாணவர்கள்',
    te: 'విద్యార్థులు',
    bn: 'শিক্ষার্থী',
  },
  analytics: {
    en: 'Analytics',
    hi: 'विश्लेषण',
    ta: 'பகுப்பாய்வு',
    te: 'విశ్లేషణ',
    bn: 'বিশ্লেষণ',
  },
  // Actions
  startLesson: {
    en: 'Start Lesson',
    hi: 'पाठ शुरू करें',
    ta: 'பாடத்தைத் தொடங்கு',
    te: 'పాఠం ప్రారంభించండి',
    bn: 'পাঠ শুরু করুন',
  },
  takeQuiz: {
    en: 'Take Quiz',
    hi: 'प्रश्नोत्तरी लें',
    ta: 'வினாடி வினா எடு',
    te: 'క్విజ్ తీసుకోండి',
    bn: 'কুইজ নিন',
  },
  submit: {
    en: 'Submit',
    hi: 'जमा करें',
    ta: 'சமர்ப்பி',
    te: 'సమర్పించు',
    bn: 'জমা দিন',
  },
  next: {
    en: 'Next',
    hi: 'अगला',
    ta: 'அடுத்து',
    te: 'తరువాత',
    bn: 'পরবর্তী',
  },
  previous: {
    en: 'Previous',
    hi: 'पिछला',
    ta: 'முந்தைய',
    te: 'మునుపటి',
    bn: 'পূর্ববর্তী',
  },
  finish: {
    en: 'Finish',
    hi: 'समाप्त',
    ta: 'முடி',
    te: 'ముగించు',
    bn: 'শেষ',
  },
  // Status
  completed: {
    en: 'Completed',
    hi: 'पूर्ण',
    ta: 'முடிந்தது',
    te: 'పూర్తయింది',
    bn: 'সম্পন্ন',
  },
  inProgress: {
    en: 'In Progress',
    hi: 'प्रगति में',
    ta: 'செயல்பாட்டில்',
    te: 'పురోగతిలో',
    bn: 'চলমান',
  },
  notStarted: {
    en: 'Not Started',
    hi: 'शुरू नहीं हुआ',
    ta: 'தொடங்கவில்லை',
    te: 'ప్రారంభించలేదు',
    bn: 'শুরু হয়নি',
  },
  // Common
  welcome: {
    en: 'Welcome',
    hi: 'स्वागत है',
    ta: 'வரவேற்பு',
    te: 'స్వాగతం',
    bn: 'স্বাগতম',
  },
  login: {
    en: 'Login',
    hi: 'लॉगिन',
    ta: 'உள்நுழைவு',
    te: 'లాగిన్',
    bn: 'লগইন',
  },
  logout: {
    en: 'Logout',
    hi: 'लॉगआउट',
    ta: 'வெளியேறு',
    te: 'లాగౌట్',
    bn: 'লগআউট',
  },
  student: {
    en: 'Student',
    hi: 'छात्र',
    ta: 'மாணவர்',
    te: 'విద్యార్థి',
    bn: 'শিক্ষার্থী',
  },
  teacher: {
    en: 'Teacher',
    hi: 'शिक्षक',
    ta: 'ஆசிரியர்',
    te: 'ఉపాధ్యాయుడు',
    bn: 'শিক্ষক',
  },
  language: {
    en: 'Language',
    hi: 'भाषा',
    ta: 'மொழி',
    te: 'భాష',
    bn: 'ভাষা',
  },
  grade: {
    en: 'Grade',
    hi: 'कक्षा',
    ta: 'வகுப்பு',
    te: 'తరగతి',
    bn: 'শ্রেণী',
  },
  score: {
    en: 'Score',
    hi: 'अंक',
    ta: 'மதிப்பெண்',
    te: 'స్కోర్',
    bn: 'স্কোর',
  },
  offline: {
    en: 'Offline Mode',
    hi: 'ऑफ़लाइन मोड',
    ta: 'ஆஃफ்லைன் பயன்முறை',
    te: 'ఆఫ్‌లైన్ మోడ్',
    bn: 'অফলাইন মোড',
  },
  achievements: {
    en: 'Achievements',
    hi: 'उपलब्धियां',
    ta: 'சாதனைகள்',
    te: 'సాధనలు',
    bn: 'অর্জন',
  },
  unlocked: {
    en: 'Unlocked',
    hi: 'अनलॉक',
    ta: 'திறக்கப்பட்டது',
    te: 'అన్‌లాక్ చేయబడింది',
    bn: 'আনলক করা হয়েছে',
  },
  digitalLiteracy: {
    en: 'Digital Literacy',
    hi: 'डिजिटल साक्षरता',
    ta: 'டிஜிட்டல் எழுத்தறிவு',
    te: 'డిజిటల్ అక్షరాస్యత',
    bn: 'ডিজিটাল সাক্ষরতা',
  },
  digitalIndia: {
    en: 'Digital India',
    hi: 'डिजिटल इंडिया',
    ta: 'டிஜிட்டல் இந்தியா',
    te: 'డిజిటల్ ఇండియా',
    bn: 'ডিজিটাল ইন্ডিয়া',
  },
  buildingSkills: {
    en: 'Building Digital Skills',
    hi: 'डिजिटल कौशल का निर्माण',
    ta: 'டிஜிட்டல் திறன்களை உருவாக்குதல்',
    te: 'డిజిటల్ నైపుణ్యాలను నిర్మించడం',
    bn: 'ডিজিটাল দক্ষতা তৈরি করা',
  },
  overallProgress: {
    en: 'Overall Progress',
    hi: 'कुल प्रगति',
    ta: 'மொத்த முன்னேற்றம்',
    te: 'మొత్తం పురోగతి',
    bn: 'সামগ্রিক অগ্রগতি',
  },
  learningStreak: {
    en: 'Learning Streak',
    hi: 'सीखने की लकीर',
    ta: 'கற்றல் தொடர்ச்சி',
    te: 'నేర్చుకునే పరంపర',
    bn: 'শেখার ধারা',
  },
  currentStreak: {
    en: 'Current Streak',
    hi: 'वर्तमान लकीर',
    ta: 'தற்போதைய தொடர்ச்சி',
    te: 'ప్రస్తుత పరంపర',
    bn: 'বর্তমান ধারা',
  },
  bestStreak: {
    en: 'Best Streak',
    hi: 'सर्वश्रेष्ठ लकीर',
    ta: 'சிறந்த தொடர்ச்சி',
    te: 'ఉత్తమ పరంపర',
    bn: 'সেরা ধারা',
  },
  last7Days: {
    en: 'Last 7 Days',
    hi: 'पिछले 7 दिन',
    ta: 'கடந்த 7 நாட்கள்',
    te: 'గత 7 రోజులు',
    bn: 'শেষ 7 দিন',
  },
  streakActive: {
    en: 'Great job! Keep your streak going',
    hi: 'बहुत बढ़िया! अपनी लकीर जारी रखें',
    ta: 'நன்றாக செய்தீர்கள்! உங்கள் தொடர்ச்சியைத் தொடரவும்',
    te: 'గొప్పగా చేసారు! మీ పరంపరను కొనసాగించండి',
    bn: 'দারুণ কাজ! আপনার ধারা চালিয়ে যান',
  },
  certificate: {
    en: 'Certificate',
    hi: 'प्रमाण पत्र',
    ta: 'சான்றிதழ்',
    te: 'సర్టిఫికేట్',
    bn: 'সার্টিফিকেট',
  },
  achievementCertificate: {
    en: 'Certificate of Achievement',
    hi: 'उपलब्धि प्रमाण पत्र',
    ta: 'சாதனை சான்றிதழ்',
    te: 'సాధన సర్టిఫికేట్',
    bn: 'অর্জন সার্টিফিকেট',
  },
  certificateOfAchievement: {
    en: 'Certificate of Achievement',
    hi: 'उपलब्धि प्रमाण पत्र',
    ta: 'சாதனைச் சான்றிதழ்',
    te: 'సాధన సర్టిఫికేట్',
    bn: 'অর্জনের সার্টিফিকেট',
  },
  ruralEducation: {
    en: 'Rural Education Initiative',
    hi: 'ग्रामीण शिक्षा पहल',
    ta: 'கிராமப்புற கல்வி முன்முயற்சி',
    te: 'గ్రామీణ విద్యా చొరవ',
    bn: 'গ্রামীণ শিক্ষা উদ্যোগ',
  },
  presentedTo: {
    en: 'This certificate is proudly presented to',
    hi: 'यह प्रमाण पत्र गर्व से प्रस्तुत किया जाता है',
    ta: 'இந்த சான்றிதழ் பெருமையுடன் வழங்கப்படுகிறது',
    te: 'ఈ సర్టిఫికేట్ గర్వంగా అందించబడింది',
    bn: 'এই সার্টিফিকেট গর্বের সাথে উপস্থাপিত',
  },
  forSuccessfully: {
    en: 'for successfully completing',
    hi: 'सफलतापूर्वक पूरा करने के लिए',
    ta: 'வெற்றிகரமாக முடித்ததற்காக',
    te: 'విజయవంతంగా పూర్తి చేసినందుకు',
    bn: 'সফলভাবে সম্পন্ন করার জন্য',
  },
  dateIssued: {
    en: 'Date Issued',
    hi: 'जारी करने की तिथि',
    ta: 'வெளியிடப்பட்ட தேதி',
    te: 'జారీ చేసిన తేదీ',
    bn: 'প্রদানের তারিখ',
  },
  teacherSignature: {
    en: 'Teacher',
    hi: 'शिक्षक',
    ta: 'ஆசிரியர்',
    te: 'ఉపాధ్యాయుడు',
    bn: 'শিক্ষক',
  },
  principalSignature: {
    en: 'Principal',
    hi: 'प्रधानाचार्य',
    ta: 'அதிபர்',
    te: 'ప్రిన్సిపాల్',
    bn: 'প্রধান শিক্ষক',
  },
  print: {
    en: 'Print',
    hi: 'प्रिंट',
    ta: 'அச்சிடு',
    te: 'ముద్రించు',
    bn: 'মুদ্রণ',
  },
  download: {
    en: 'Download',
    hi: 'डाउनलोड',
    ta: 'பதிவிறக்கு',
    te: 'డౌన్‌లోడ్',
    bn: 'ডাউনলোড',
  },
  viewCertificate: {
    en: 'View Certificate',
    hi: 'प्रमाण पत्र देखें',
    ta: 'சான்றிதழைப் பார்க்கவும்',
    te: 'సర్టిఫికేట్ చూడండి',
    bn: 'সার্টিফিকেট দেখুন',
  },
  earnedBadges: {
    en: 'Earned Badges',
    hi: 'अर्जित बैज',
    ta: 'பெற்ற பதக்கங்கள்',
    te: 'సంపాదించిన బ్యాడ్జ్‌లు',
    bn: 'অর্জিত ব্যাজ',
  },
};

export const getTranslation = (key: string, language: Language): string => {
  return translations[key]?.[language] || key;
};